name: Tenant Improvement Glass
favicon: null
layout_spectrum: 0.7031119645107538
typography_spectrum: 0.13868899480439723
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.42605515848845243
  lightness: 0.0794625822454691
  saturation: 0.9545946400612593
  rhythmicContrast: 0.24236872792243958
purpose: []
